[package]
name = "process-wrap"
version = "5.0.1"

authors = ["Félix Saparelli <felix@passcod.name>"]
license = "Apache-2.0 OR MIT"
description = "Wrap a Command, to spawn processes in a group or session or pty etc"
keywords = ["command", "process", "group", "session", "pty"]

documentation = "https://docs.rs/process-wrap"
homepage = "https://github.com/watchexec/process-wrap"
repository = "https://github.com/watchexec/process-wrap"
readme = "README.md"

edition = "2021"
exclude = ["/bin", "/.github"]
rust-version = "1.75.0"

# there are a few windows-specific ones
autoexamples = false

[dependencies.tokio]
version = "1.33.0"
features = ["io-util", "macros", "process", "rt"]
optional = true

[target.'cfg(unix)'.dependencies.nix]
version = "0.27.1"
default-features = false
features = ["fs", "poll", "signal"]
optional = true

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.9"
features = [
	"impl-default",
	"handleapi",
	"ioapiset",
	"jobapi2",
	"processthreadsapi",
	"tlhelp32",
	"winbase",
]
optional = true

[features]
default = ["std", "tokio1", "creation-flags", "job-object", "process-group", "process-session"]

## Frontend: StdCommandWrap
std = []

## Frontend: TokioCommandWrap
tokio1 = ["dep:tokio"]

## Wrapper: Creation Flags
creation-flags = ["dep:winapi"]

## Wrapper: Job Object
job-object = ["dep:winapi"]

## Wrapper: Process Group
process-group = ["dep:nix"]

## Wrapper: Process Session
process-session = ["dep:nix"]

## Wrapper: Pty (TODO)
pty = []


[dev-dependencies]
tokio = { version = "1.10.0", features = ["io-util", "macros", "process", "rt", "rt-multi-thread", "time"] }

[package.metadata.docs.rs]
all-features = true

[dependencies]
indexmap = "2.2.5"
tracing = "0.1.40"
